In [52]:
import pandas as pd
import yfinance as yf
import pandas_gbq
from time import time
import warnings

warnings.filterwarnings("ignore", category=DeprecationWarning)

project_id = "example"

In [53]:
tickers = yf.Tickers('AAPL MSFT GOOGL AMZN TSLA NVDA META BRK.A V JNJ WMT DIS PYPL AMD CSCO INTC BA GE PG MA VZ IBM NVAX ADBE NFLX PEP BABA GM XOM CVX KO MRK ABT PFE TXN UNH UNP MMM MDT GILD SBUX CAT GS LMT UPS NKE HD ORCL INTU F SPG BA WFC C TGT MCD LULU TMO AIG SYK AMGN CVS BMY MS DE ZTS LOW CSX TJX MMM BLK SYY MCO FDX GS CHTR RTX COP')

In [54]:
tickers.tickers['MSFT'].info

{'address1': 'One Microsoft Way',
 'city': 'Redmond',
 'state': 'WA',
 'zip': '98052-6399',
 'country': 'United States',
 'phone': '425 882 8080',
 'website': 'https://www.microsoft.com',
 'industry': 'Software - Infrastructure',
 'industryKey': 'software-infrastructure',
 'industryDisp': 'Software - Infrastructure',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Microsoft Corporation develops and supports software, services, devices and solutions worldwide. The Productivity and Business Processes segment offers office, exchange, SharePoint, Microsoft Teams, office 365 Security and Compliance, Microsoft viva, and Microsoft 365 copilot; and office consumer services, such as Microsoft 365 consumer subscriptions, Office licensed on-premises, and other office services. This segment also provides LinkedIn; and dynamics business solutions, including Dynamics 365, a set of intelligent, cloud-based applications across ERP, CRM, power apps, and power automate; and on-premises ERP and CRM applications. The Intelligent Cloud segment offers server products and cloud services, such as azure and other cloud services; SQL and windows server, visual studio, system center, and related client access licenses, as well as nuance and GitHub; and enterprise services including enterprise support services, industry solutions, and nuance professional services. The More Personal Computing segment offers Windows, including windows OEM licensing and other non-volume licensing of the Windows operating system; Windows commercial comprising volume licensing of the Windows operating system, windows cloud services, and other Windows commercial offerings; patent licensing; and windows Internet of Things; and devices, such as surface, HoloLens, and PC accessories. Additionally, this segment provides gaming, which includes Xbox hardware and content, and first- and third-party content; Xbox game pass and other subscriptions, cloud gaming, advertising, third-party disc royalties, and other cloud services; and search and news advertising, which includes Bing, Microsoft News and Edge, and third-party affiliates. The company sells its products through OEMs, distributors, and resellers; and directly through digital marketplaces, online, and retail stores. The company was founded in 1975 and is headquartered in Redmond, Washington.',
 'fullTimeEmployees': 228000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Satya  Nadella',
   'age': 57,
   'title': 'Chairman & CEO',
   'yearBorn': 1967,
   'fiscalYear': 2024,
   'totalPay': 7869791,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Bradford L. Smith LCA',
   'age': 65,
   'title': 'President & Vice Chairman',
   'yearBorn': 1959,
   'fiscalYear': 2024,
   'totalPay': 4755618,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Amy E. Hood',
   'age': 52,
   'title': 'Executive VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2024,
   'totalPay': 4704250,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Judson B. Althoff',
   'age': 51,
   'title': 'Executive VP & Chief Commercial Officer',
   'yearBorn': 1973,
   'fiscalYear': 2024,
   'totalPay': 4534974,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Christopher David Young',
   'age': 52,
   'title': 'Executive Vice President of Business Development, Strategy & Ventures',
   'yearBorn': 1972,
   'fiscalYear': 2024,
   'totalPay': 2993772,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Carolina  Dybeck Happe',
   'age': 52,
   'title': 'Executive VP & COO',
   'yearBorn': 1972,
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Alice L. Jolla',
   'age': 58,
   'title': 'Corporate VP & Chief Accounting Officer',
   'yearBorn': 1966,
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. James Kevin Scott',
   'age': 52,
   'title': 'Executive VP of AI & CTO',
   'yearBorn': 1972,
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Brett  Iversen',
   'title': 'Vice President of Investor Relations',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Hossein  Nowbar',
   'title': 'Chief Legal Officer',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 9,
 'boardRisk': 5,
 'compensationRisk': 3,
 'shareHolderRightsRisk': 2,
 'overallRisk': 3,
 'governanceEpochDate': 1735689600,
 'compensationAsOfEpochDate': 1735603200,
 'irWebsite': 'http://www.microsoft.com/investor/default.aspx',
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 424.58,
 'open': 434.09,
 'dayLow': 428.17,
 'dayHigh': 434.39,
 'regularMarketPreviousClose': 424.58,
 'regularMarketOpen': 434.09,
 'regularMarketDayLow': 428.17,
 'regularMarketDayHigh': 434.39,
 'dividendRate': 3.32,
 'dividendYield': 0.0077,
 'exDividendDate': 1740009600,
 'payoutRatio': 0.2477,
 'fiveYearAvgDividendYield': 0.86,
 'beta': 0.904,
 'trailingPE': 35.457024,
 'forwardPE': 28.583687,
 'volume': 25262115,
 'regularMarketVolume': 25262115,
 'averageVolume': 21171277,
 'averageVolume10days': 18625780,
 'averageDailyVolume10Day': 18625780,
 'bid': 428.37,
 'ask': 428.69,
 'bidSize': 700,
 'askSize': 100,
 'marketCap': 3189786542080,
 'fiftyTwoWeekLow': 385.58,
 'fiftyTwoWeekHigh': 468.35,
 'priceToSalesTrailing12Months': 12.548828,
 'fiftyDayAverage': 428.718,
 'twoHundredDayAverage': 425.13504,
 'trailingAnnualDividendRate': 3.08,
 'trailingAnnualDividendYield': 0.0072542275,
 'currency': 'USD',
 'enterpriseValue': 3208195866624,
 'profitMargins': 0.35608003,
 'floatShares': 7424694989,
 'sharesOutstanding': 7434880000,
 'sharesShort': 62178630,
 'sharesShortPriorMonth': 63089851,
 'sharesShortPreviousMonthDate': 1732838400,
 'dateShortInterest': 1735603200,
 'sharesPercentSharesOut': 0.0084,
 'heldPercentInsiders': 0.00056,
 'heldPercentInstitutions': 0.73657995,
 'shortRatio': 2.97,
 'shortPercentOfFloat': 0.0084,
 'impliedSharesOutstanding': 7434880000,
 'bookValue': 38.693,
 'priceToBook': 11.088052,
 'lastFiscalYearEnd': 1719705600,
 'nextFiscalYearEnd': 1751241600,
 'mostRecentQuarter': 1727654400,
 'earningsQuarterlyGrowth': 0.107,
 'netIncomeToCommon': 90511998976,
 'trailingEps': 12.1,
 'forwardEps': 14.95,
 'lastSplitFactor': '2:1',
 'lastSplitDate': 1045526400,
 'enterpriseToRevenue': 12.621,
 'enterpriseToEbitda': 23.494,
 '52WeekChange': 0.08201563,
 'SandP52WeekChange': 0.23631513,
 'lastDividendValue': 0.83,
 'lastDividendDate': 1732147200,
 'exchange': 'NMS',
 'quoteType': 'EQUITY',
 'symbol': 'MSFT',
 'underlyingSymbol': 'MSFT',
 'shortName': 'Microsoft Corporation',
 'longName': 'Microsoft Corporation',
 'firstTradeDateEpochUtc': 511108200,
 'timeZoneFullName': 'America/New_York',
 'timeZoneShortName': 'EST',
 'uuid': 'b004b3ec-de24-385e-b2c1-923f10d3fb62',
 'messageBoardId': 'finmb_21835',
 'gmtOffSetMilliseconds': -18000000,
 'currentPrice': 429.03,
 'targetHighPrice': 650.0,
 'targetLowPrice': 420.0,
 'targetMeanPrice': 508.4636,
 'targetMedianPrice': 500.0,
 'recommendationMean': 1.41379,
 'recommendationKey': 'strong_buy',
 'numberOfAnalystOpinions': 50,
 'totalCash': 78429003776,
 'totalCashPerShare': 10.549,
 'ebitda': 136551997440,
 'totalDebt': 96838000640,
 'quickRatio': 1.163,
 'currentRatio': 1.301,
 'totalRevenue': 254189993984,
 'debtToEquity': 33.657,
 'revenuePerShare': 34.202,
 'returnOnAssets': 0.14592,
 'returnOnEquity': 0.35604,
 'grossProfits': 176278994944,
 'freeCashflow': 61280874496,
 'operatingCashflow': 122144997376,
 'earningsGrowth': 0.104,
 'revenueGrowth': 0.16,
 'grossMargins': 0.69348997,
 'ebitdaMargins': 0.53720003,
 'operatingMargins': 0.46583998,
 'financialCurrency': 'USD',
 'trailingPegRatio': 2.2522}

In [55]:
df = yf.download(["AAPL", "MSFT", "GOOGL", "AMZN", "TSLA", "NVDA", "META", "V", "JNJ", "WMT", "DIS", "PYPL", "AMD", "CSCO", "INTC", "BA", "GE", "PG", "MA", "VZ", "IBM", "NVAX", "ADBE", 
             "NFLX", "PEP", "BABA", "GM", "XOM", "CVX", "KO", "MRK", "ABT", "PFE", "TXN", "UNH", "UNP", "MMM", "MDT", "GILD", "SBUX", "CAT", "GS", "LMT", "UPS", "NKE", "HD", "ORCL", 
             "INTU", "F", "SPG", "BA", "WFC", "C", "TGT", "MCD", "LULU", "TMO", "AIG", "SYK", "AMGN", "CVS", "BMY", "MS", "DE", "ZTS", "LOW", "CSX", "TJX", "MMM", "BLK", "SYY", "MCO", 
             "FDX", "GS", "CHTR", "RTX", "COP", "LMT", "MELI", "COST"], period="10Y")

[*********************100%***********************]  76 of 76 completed

In [56]:
df

Price            Close                                                 \
Ticker            AAPL         ABT        ADBE        AIG         AMD
Date
2015-01-20   24.211332   36.548405   71.489998  39.727539    2.240000
2015-01-21   24.396160   36.416161   71.540001  39.868725    2.450000
2015-01-22   25.030846   36.771564   73.480003  41.006042    2.470000
2015-01-23   25.160009   36.250854   74.059998  40.402084    2.450000
2015-01-26   25.186729   36.490540   72.739998  40.166775    2.610000
...                ...         ...         ...        ...         ...
2025-01-13  234.399994  112.599121  408.500000  70.839996  117.320000
2025-01-14  233.279999  112.430000  412.709991  72.589996  116.089996
2025-01-15  237.869995  111.099998  417.279999  73.070000  119.959999
2025-01-16  228.259995  113.910004  426.929993  74.610001  118.440002
2025-01-17  229.979996  113.480003  429.989990  75.089996  121.459999

Price                                                                    ...  \
Ticker            AMGN        AMZN          BA        BABA          BLK  ...
Date                                                                     ...
2015-01-20  118.504677   14.472000  114.767990   96.613297   268.909271  ...
2015-01-21  118.339264   14.862500  115.808792   99.751968   271.167084  ...
2015-01-22  119.985931   15.516000  118.633827  100.437645   279.926758  ...
2015-01-23  120.166435   15.619500  117.741707   99.578133   275.527435  ...
2015-01-26  120.106224   15.483000  117.260681  100.427986   277.288696  ...
...                ...         ...         ...         ...          ...  ...
2025-01-13  270.190002  218.460007  170.570007   80.540001   955.010010  ...
2025-01-14  267.100006  217.759995  167.020004   81.680000   963.169983  ...
2025-01-15  268.940002  223.350006  166.199997   82.440002  1013.179993  ...
2025-01-16  269.429993  220.660004  168.929993   82.430000   995.719971  ...
2025-01-17  272.109985  225.940002  171.089996   85.120003  1004.960022  ...

Price        Volume                                                            \
Ticker          TXN      UNH      UNP       UPS         V        VZ       WFC
Date
2015-01-20  7213400  6526800  5446200   4124800  14933200  16460300  17691000
2015-01-21  5468900  8293700  4783600   2144300   9784000  24880200  17928300
2015-01-22  5484200  8055200  6430700   3008100  11566000  38451100  21488700
2015-01-23  4856500  5256000  5124100  19275400   6166800  24317800  17779700
2015-01-26  6137000  4203400  3550800  10903700   8552400  15064400  13429400
...             ...      ...      ...       ...       ...       ...       ...
2025-01-13  4799600  6472500  2278100   6939200   9568400  19734000  10439800
2025-01-14  4254200  3978300  1823400   4247600   5107600  15740100  21909800
2025-01-15  6288600  4103900  1892300   4315900   5222000  27817100  33482900
2025-01-16  7463300  9059900  2296900   5471300   4606700  24678300  22897900
2025-01-17  5388500  7462900  3643700   4260300   5746200  23988300  20610100

Price
Ticker           WMT       XOM      ZTS
Date
2015-01-20  23559300  16761000  3471000
2015-01-21  24521400  14276400  1991900
2015-01-22  21371400  13559000  2914700
2015-01-23  22697400  14706300  2885500
2015-01-26  14000100  10672500  1926800
...              ...       ...      ...
2025-01-13  18617100  17073400  2306100
2025-01-14  13549200  11191200  3608200
2025-01-15  17348200  14521100  2988300
2025-01-16  13267700  10366600  2804400
2025-01-17  15706100  19229100  4656700

[2516 rows x 380 columns]

In [57]:
closedf = df['Close']
highdf = df['High']
voldf = df['Volume']
opendf = df['Open']
lowdf = df['Low']

In [58]:
closedf

Ticker,AAPL,ABT,ADBE,AIG,AMD,AMGN,AMZN,BA,BABA,BLK,...,TXN,UNH,UNP,UPS,V,VZ,WFC,WMT,XOM,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2015-01-20,24.211332,36.548405,71.489998,39.727539,2.240000,118.504677,14.472000,114.767990,96.613297,268.909271,...,41.094311,90.718079,91.146255,80.190666,59.869892,28.971994,39.007027,23.657080,58.917091,40.587627
2015-01-21,24.396160,36.416161,71.540001,39.868725,2.450000,118.339264,14.862500,115.808792,99.751968,271.167084,...,41.453239,93.896072,91.506218,80.457222,59.972462,29.014086,39.082039,23.643436,59.421604,41.230522
2015-01-22,25.030846,36.771564,73.480003,41.006042,2.470000,119.985931,15.516000,118.633827,100.437645,279.926758,...,41.980194,97.786919,95.849548,82.308716,60.047054,28.743484,40.334770,24.096426,60.068413,41.472794
2015-01-23,25.160009,36.250854,74.059998,40.402084,2.450000,120.166435,15.619500,117.741707,99.578133,275.527435,...,42.048931,96.197945,96.057526,74.153496,60.207878,28.352629,39.952202,24.153742,58.787754,41.109390
2015-01-26,25.186729,36.490540,72.739998,40.166775,2.610000,120.106224,15.483000,117.260681,100.427986,277.288696,...,42.041283,95.862961,97.049362,73.735634,59.797615,28.238371,40.192249,24.186485,59.350452,41.081448
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-01-13,234.399994,112.599121,408.500000,70.839996,117.320000,270.190002,218.460007,170.570007,80.540001,955.010010,...,191.089996,541.140015,226.759995,125.010002,306.920013,38.119999,70.529999,91.529999,109.290001,166.320007
2025-01-14,233.279999,112.430000,412.709991,72.589996,116.089996,267.100006,217.759995,167.020004,81.680000,963.169983,...,193.500000,543.739990,229.380005,125.839996,309.089996,38.279999,71.190002,90.790001,109.720001,164.410004
2025-01-15,237.869995,111.099998,417.279999,73.070000,119.959999,268.940002,223.350006,166.199997,82.440002,1013.179993,...,197.509995,543.419983,230.860001,127.470001,316.279999,38.180000,75.949997,91.339996,111.510002,167.169998
2025-01-16,228.259995,113.910004,426.929993,74.610001,118.440002,269.429993,220.660004,168.929993,82.430000,995.719971,...,187.369995,510.589996,234.889999,129.940002,317.250000,38.340000,75.949997,91.300003,111.320000,169.369995
2025-01-17,229.979996,113.480003,429.989990,75.089996,121.459999,272.109985,225.940002,171.089996,85.120003,1004.960022,...,192.419998,509.760010,234.259995,129.729996,319.619995,38.779999,77.080002,91.940002,112.320000,165.889999

In [59]:
table_id = "example.smdata.Close"

In [60]:
max_chunks = 10 
counter = 0

while counter < max_chunks:
    t_start = time()
    pandas_gbq.to_gbq(closedf, table_id, project_id=project_id, chunksize=100000, if_exists='append')
    t_end = time()

    print('Inserted another chunk... took %.3f second ' % (t_end - t_start))
    
    counter += 1
    print(f'Processed chunk {counter}/{max_chunks}')

Inserted another chunk... took 4.252 second
Processed chunk 1/10
Inserted another chunk... took 4.023 second
Processed chunk 2/10
Inserted another chunk... took 4.651 second
Processed chunk 3/10
Inserted another chunk... took 3.941 second
Processed chunk 4/10
Inserted another chunk... took 11.905 second
Processed chunk 5/10
Inserted another chunk... took 4.025 second
Processed chunk 6/10
Inserted another chunk... took 3.568 second
Processed chunk 7/10
Inserted another chunk... took 4.202 second
Processed chunk 8/10
Inserted another chunk... took 5.235 second
Processed chunk 9/10
Inserted another chunk... took 3.145 second
Processed chunk 10/10

In [61]:
table_id = 'example.smdata.Open'

max_chunks = 10 
counter = 0

while counter < max_chunks:
    t_start = time()
    pandas_gbq.to_gbq(opendf, table_id, project_id=project_id, chunksize=100000, if_exists='append')
    t_end = time()

    print('Inserted another chunk... took %.3f second ' % (t_end - t_start))
    
    counter += 1
    print(f'Processed chunk {counter}/{max_chunks}')

Inserted another chunk... took 4.181 second
Processed chunk 1/10
Inserted another chunk... took 3.540 second
Processed chunk 2/10
Inserted another chunk... took 3.909 second
Processed chunk 3/10
Inserted another chunk... took 4.340 second
Processed chunk 4/10
Inserted another chunk... took 3.612 second
Processed chunk 5/10
Inserted another chunk... took 2.948 second
Processed chunk 6/10
Inserted another chunk... took 3.787 second
Processed chunk 7/10
Inserted another chunk... took 4.192 second
Processed chunk 8/10
Inserted another chunk... took 3.140 second
Processed chunk 9/10
Inserted another chunk... took 4.085 second
Processed chunk 10/10

In [62]:
table_id = "example.smdata.Low"

max_chunks = 10 
counter = 0

while counter < max_chunks:
    t_start = time()
    pandas_gbq.to_gbq(lowdf, table_id, project_id=project_id, chunksize=100000, if_exists='append')
    t_end = time()

    print('Inserted another chunk... took %.3f second ' % (t_end - t_start))
    
    counter += 1
    print(f'Processed chunk {counter}/{max_chunks}')

Inserted another chunk... took 3.648 second
Processed chunk 1/10
Inserted another chunk... took 5.403 second
Processed chunk 2/10
Inserted another chunk... took 3.079 second
Processed chunk 3/10
Inserted another chunk... took 4.709 second
Processed chunk 4/10
Inserted another chunk... took 4.876 second
Processed chunk 5/10
Inserted another chunk... took 3.559 second
Processed chunk 6/10
Inserted another chunk... took 6.566 second
Processed chunk 7/10
Inserted another chunk... took 4.076 second
Processed chunk 8/10
Inserted another chunk... took 3.489 second
Processed chunk 9/10
Inserted another chunk... took 4.911 second
Processed chunk 10/10

In [63]:
table_id = "example.smdata.Volume"

max_chunks = 10 
counter = 0

while counter < max_chunks:
    t_start = time()
    pandas_gbq.to_gbq(voldf, table_id, project_id=project_id, chunksize=100000, if_exists='append')
    t_end = time()

    print('Inserted another chunk... took %.3f second ' % (t_end - t_start))
    
    counter += 1
    print(f'Processed chunk {counter}/{max_chunks}')

Inserted another chunk... took 3.424 second
Processed chunk 1/10
Inserted another chunk... took 3.708 second
Processed chunk 2/10
Inserted another chunk... took 3.557 second
Processed chunk 3/10
Inserted another chunk... took 3.144 second
Processed chunk 4/10
Inserted another chunk... took 3.899 second
Processed chunk 5/10
Inserted another chunk... took 4.193 second
Processed chunk 6/10
Inserted another chunk... took 3.113 second
Processed chunk 7/10
Inserted another chunk... took 2.951 second
Processed chunk 8/10
Inserted another chunk... took 4.825 second
Processed chunk 9/10
Inserted another chunk... took 3.848 second
Processed chunk 10/10

In [64]:
table_id = "example.smdata.High"

max_chunks = 10 
counter = 0

while counter < max_chunks:
    t_start = time()
    pandas_gbq.to_gbq(highdf, table_id, project_id=project_id, chunksize=100000, if_exists='append')
    t_end = time()

    print('Inserted another chunk... took %.3f second ' % (t_end - t_start))
    
    counter += 1
    print(f'Processed chunk {counter}/{max_chunks}')

Inserted another chunk... took 5.044 second
Processed chunk 1/10
Inserted another chunk... took 5.137 second
Processed chunk 2/10
Inserted another chunk... took 4.313 second
Processed chunk 3/10
Inserted another chunk... took 3.637 second
Processed chunk 4/10
Inserted another chunk... took 4.109 second
Processed chunk 5/10
Inserted another chunk... took 3.152 second
Processed chunk 6/10
Inserted another chunk... took 4.189 second
Processed chunk 7/10
Inserted another chunk... took 3.252 second
Processed chunk 8/10
Inserted another chunk... took 3.258 second
Processed chunk 9/10
Inserted another chunk... took 3.844 second
Processed chunk 10/10